name: Trigger build and deploy

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'

jobs:
  log-context:
    steps:
      - name: Log context
        run: echo "${{ github.repository_owner }}"

  call-build-deploy:
    uses: nicholasmakhija/workflow-sandbox/.github/workflows/build-deploy.yml@main