name: Trigger build and deploy

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'

jobs:
  # log-context:
  #   env:
  #     REPO: ${{ github.repository }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Log local env
  #       run: echo "$REPO"

  call-build-deploy:
    env:
      REPO: ${{ github.repository }}
    # uses: nicholasmakhija/workflow-sandbox/.github/workflows/build-deploy.yml@main
    uses: "$REPO/.github/workflows/build-deploy.yml@main"